PR -Smart door lock; plz review it
marsiitr/Smart-door-locking-system pull request #2
Opened 2022-07-23 21:59 UTC by ashtikarmanmath

2022-07-24 09:57 UTC, Nageshbansal commented on README.md
> +<img width="674" alt="Final ckt" src="https://user-images.githubusercontent.com/109852675/180622980-73ec9dae-7ab8-48cd-b12d-f95311ac56dc.png">
<img/> tags should be in ```<p></p>```, so that image can align in  center.

2022-07-24 09:57 UTC, Nageshbansal commented on README.md
> +## Cost Structure
cost of components should be in a table.
```
----------------------------
components |  Price |
----------------------------
```

2022-07-24 09:57 UTC, Nageshbansal commented on README.md
> +	1. Manmanth Ashtikar   (https://github.com/ashtikarmanmath)
you can use hyperlinks. ```[name](url)```

2022-07-24 09:57 UTC, Nageshbansal commented on src/NodeMCU code/Untitled_jun16a/thingProperties.h
> +const char DEVICE_LOGIN_NAME[]  = "bd95aeec-8969-4784-8675-a7cdd2077f8d";
"DEVICE NAME"

2022-08-07 19:04 UTC, Nageshbansal reviewed
1. add a report in the ```Poster and Report directory```
2. all images in readme should be of same size and you need to add these images in ```<p></p>``` tags to align them in the center
3. add links of the mentor's github profile also

2022-08-07 19:05 UTC, Nageshbansal commented
And resolve the previous configuration ASAP

2022-08-19 13:07 UTC, SanjeevKrishnan commented
Do not create multiple PRs. Close the unnecessary PRs. Finish your documentation ASAP.
@Nageshbansal Follow this up and tag me once the PR is ready for merge.

2022-08-21 16:32 UTC, Chakri2507 commented
[Report.pdf](https://github.com/marsiitr/Smart-door-locking-system/files/9389565/Report.pdf)

2022-08-25 17:37 UTC, Nageshbansal requested changes
@ashtikarmanmath Thanks for the PR, there are some changes you need to do:
1. Report in the `.pdf` format
2. Code should be in the respective file format .i.e Arduino code in the `.ino` file not in the `.txt` file
3. File names should be according to the given guidelines
4. Justify the text in README.md
5. Links to Mentor's GitHub profile
And Let me know when you're done with the changes

2026-05-24 13:09 UTC, merged